models.py
from datetime import datetime
import re
from app import db

from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags',
                    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Tage id: {self.id}, name: {self.name}'

### Flask Security

roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id')),
    )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from config import Configuration
from posts.blueprint import posts

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore, Security

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(posts, url_prefix='/blog')

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

from models import *
admin = Admin(app)
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Tag, db.session))

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

@app.route('/')
@app.route('/index')
def index():
    name = 'mezgoodle'
    return render_template('index.html', name=name)


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from models import Post, Tag
from .forms import PostForm
from app import db

from flask import Blueprint, render_template, request, redirect, url_for
from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form('title')
        body = request.form('body')
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something is going wrong')
        return redirect(url_for('posts.index'))
    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) # .all()
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new Post
{% endblock %}
{% block content_title %}
    New post
{% endblock %}
{% block content %}
    <div class="col-md-6">
        <form action="{{url_for('posts.create_post')}}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{field.label(class='control-label')}}
                    {{field(class='form-control')}}
                </div>
            {% endfor %}
            <button class="btn btn-success" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit new Post
{% endblock %}
{% block content_title %}
    Edit post
{% endblock %}
{% block content %}
    <div class="col-md-6">
        <form action="{{url_for('posts.edit_post', slug=post.slug)}}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{field.label(class='control-label')}}
                    {{field(class='form-control')}}
                </div>
            {% endfor %}
            <button class="btn btn-success" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint
{% endblock %}
{% block content_title %}
    Posts
{% endblock %}
{% block content %}
    {% for post in pages.items %}
        <p>{{post.title}}</p>
        <a href="{{url_for('posts.post_detail', slug=post.slug)}}">{{post.title}}</a>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
          <li
            {% if not pages.has_prev %}
                class="page-link disabled"
            {% else %}
                class="page-link"
            {% endif %}
          ><a class="page-link" href="./?page={{pages.prev_num}}">Previous</a></li>
          {% for page in pages.iter_pages %}
          <li
          {% if page == pages.page %}
              class="page-link active"
          {% endif %}
            ><a class="page-link" href="./?page={{page}}">{{page}}</a></li>
          {% endfor %}
          <li
            {% if not pages.has_next %}
                class="page-link disabled"
            {% else %}
                class="page-link"
            {% endif %}
          ><a class="page-link" href="./?page={{pages.next_num}}">Next</a></li>
        </ul>
    </nav>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{post.title}}
{% endblock %}
{% block content_title %}
    {{post.title}}
{% endblock %}
{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="label label-primary">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>
    <div class="main-content">
        {{post.body}}
    </div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{tag.name}} posts
{% endblock %}
{% block content_title %}
    Posts for "{{tag.name}}" tag:
{% endblock %}
{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{url_for ('posts.post_detail', slug=post.slug)}}">{{post.title}}</a>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <title>{% block title %}Hello there!{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('posts.index') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('posts.create_post')}}">+ New post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" method="GET" action="">
              <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{request.args.get('q', '')}}">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <h1>
                {% block content_title %}
                {% endblock %}
            </h1>
            {% block content %}
            {% endblock %}
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    Index page
{% endblock %}
{% block content_title %}
    Index page
{% endblock %}
{% block content %}
    Some content
{% endblock %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content_title %}
  {{ _('Login') }}
{% endblock %}

{% block content %}
  <div class="col-md-offset-3 col-md-6">
    {% from "security/_macros.html" import render_field_with_errors, render_field %}
    {% include "security/_messages.html" %}
    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
      {{ login_user_form.hidden_tag() }}
      {{ render_field_with_errors(login_user_form.email, class='form-control') }}
      {{ render_field_with_errors(login_user_form.password, class='form-control') }}
      {{ render_field_with_errors(login_user_form.remember) }}
      {{ render_field(login_user_form.next) }}
      {{ render_field(login_user_form.submit, class='btn btn-success') }}
    </form>
    {% include "security/_menu.html" %}
  </div>
{% endblock %}